apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Thanabodin19/PYUI-GPT-Deploy.git
    targetRevision: helm-airflow
    path: airflow
  destination:
    server: https://kubernetes.default.svc