# Images
images:
  airflow:
    repository: pyui-airflow
    tag: 0.0.12
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

config:
  api:
    auth_backend: 'airflow.api.auth.backend.basic_auth'
  logging:
    remote_logging: 'True'
    remote_log_conn_id: 'minio_conn'
    remote_base_log_folder: 's3://airflow-logs'
    encrypt_s3_logs: 'False'
    colored_console_log: True
  core:
    remote_logging: "True"
    remote_log_conn_id: minio_conn

executor: "KubernetesExecutor"

# volumeMounts:
#   - name: airflow-tmp-volume
#     mountPath: /opt/airflow/tmp

# volumes:
#   - name: airflow-tmp-volume
#     persistentVolumeClaim:
#       claimName: airflow-tmp-pvc

webserver:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 4Gi

  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 300
    failureThreshold: 20
    periodSeconds: 60
    scheme: HTTP

  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 300
    failureThreshold: 20
    periodSeconds: 60
    scheme: HTTP

  startupProbe:
    timeoutSeconds: 20
    failureThreshold: 6
    periodSeconds: 300
    scheme: HTTP