apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec: 
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongodb
          image: mongo:8.0.5
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
          envFrom:
            - secretRef:
                name: mongodb-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
          limits:
            storage: 30Gi
