# Images
images:
  airflow:
    repository: pyui-airflow
    tag: t0.0.3
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

config:
  api:
    auth_backend: 'airflow.api.auth.backend.basic_auth'
  logging:
    remote_logging: 'True'
    remote_log_conn_id: 'minio_conn'
    remote_base_log_folder: 's3://airflow-logs'
    encrypt_s3_logs: 'False'
    colored_console_log: True
  core:
    remote_logging: "True"
    remote_log_conn_id: minio_conn

executor: "KubernetesExecutor"

volumeMounts:
  - name: airflow-tmp-volume
    mountPath: /opt/airflow/tmp

volumes:
  - name: airflow-tmp-volume
    persistentVolumeClaim:
      claimName: airflow-tmp-pvc
