apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyui-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyui-api
  template:
    metadata:
      labels:
        app: pyui-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: pyui-api
        image: thanabodin/pyui-api:t0.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
            ephemeral-storage: "2Gi"
        envFrom:
            - secretRef:
                name: pyui-api-secrets

