apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyui-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyui-api
  template:
    metadata:
      labels:
        app: pyui-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: pyui-api
        image: thanabodin/pyui-api:v0.2.4-beta
        ports:
        - containerPort: 80
        envFrom:
            - secretRef:
                name: pyui-api-secrets
        resources:
          requests:
            memory: "3Gi"
            cpu: "1000m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "5Gi"
            # cpu: "2000m"
            ephemeral-storage: "2Gi"

