apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  serviceName: "minio"
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pyui-s3
          image: minio/minio:RELEASE.2025-02-07T23-21-09Z
          args:
          - server
          - /data
          - "--console-address=:9001"
          envFrom:
              - secretRef:
                  name: minio-secrets
          ports:
          - containerPort: 9000
          - containerPort: 9001
          volumeMounts:
          - name: data
            mountPath: /data  # Mount PVC here
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
  volumeClaimTemplates:
  - metadata:
      name: data  # Name should match the name in volumeMounts
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
        limits:
          storage: 30Gi
